cc_library(
    name = "uring",
    srcs = ["uring.cc"],
    hdrs = ["uring.hh"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//src/lib:function",
        "//src/lib:log",
        "//src/lib:result",
        "@liburing",
    ],
)
